source_files = main.c
compiler_flags = -DDEBUG -fms-extensions -Zi -Xclang -fdeclspec -D_CRT_SECURE_NO_WARNINGS
include_path =
disable_warnings = -Wno-pointer-bool-conversion
link_flags =
executable = foreach.exe
project_dir = .
